# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `actiontext` gem.
# Please instead update this file by running `bin/tapioca gem actiontext`.

# :markup: markdown
# :include: ../README.md
#
# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:3
module ActionText
  extend ::ActiveSupport::Autoload

  class << self
    # source://actiontext-7.1.5.2/lib/action_text/deprecator.rb:4
    def deprecator; end

    # Returns the currently loaded version of Action Text as a +Gem::Version+.
    #
    # source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:5
    def gem_version; end

    # source://actiontext-7.1.5.2/lib/action_text.rb:47
    def html_document_class; end

    # source://actiontext-7.1.5.2/lib/action_text.rb:53
    def html_document_fragment_class; end

    # source://railties-7.1.5.2/lib/rails/engine.rb:412
    def railtie_helpers_paths; end

    # source://railties-7.1.5.2/lib/rails/engine.rb:395
    def railtie_namespace; end

    # source://railties-7.1.5.2/lib/rails/engine.rb:416
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://railties-7.1.5.2/lib/rails/engine.rb:401
    def table_name_prefix; end

    # source://railties-7.1.5.2/lib/rails/engine.rb:408
    def use_relative_model_naming?; end

    # Returns the currently loaded version of Action Text as a +Gem::Version+.
    #
    # source://actiontext-7.1.5.2/lib/action_text/version.rb:7
    def version; end
  end
end

# = Action Text \Attachable
#
# Include this module to make a record attachable to an ActionText::Content.
#
#   class Person < ApplicationRecord
#     include ActionText::Attachable
#   end
#
#   person = Person.create! name: "Javan"
#   html = %Q(<action-text-attachment sgid="#{person.attachable_sgid}"></action-text-attachment>)
#   content = ActionText::Content.new(html)
#   content.attachables # => [person]
#
# source://actiontext-7.1.5.2/lib/action_text/attachable.rb:16
module ActionText::Attachable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attachable::ClassMethods

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:81
  def attachable_content_type; end

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:85
  def attachable_filename; end

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:89
  def attachable_filesize; end

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:93
  def attachable_metadata; end

  # Returns the Signed Global ID for the attachable. The purpose of the ID is
  # set to 'attachable' so it can't be reused for other purposes.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:77
  def attachable_sgid; end

  # @return [Boolean]
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:97
  def previewable_attachable?; end

  # Returns the path to the partial that is used for rendering the attachable.
  # Defaults to +to_partial_path+.
  #
  # Override to render a different partial:
  #
  #   class User < ApplicationRecord
  #     def to_attachable_partial_path
  #       "users/attachable"
  #     end
  #   end
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:125
  def to_attachable_partial_path; end

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:129
  def to_rich_text_attributes(attributes = T.unsafe(nil)); end

  # Returns the path to the partial that is used for rendering the attachable
  # in Trix. Defaults to +to_partial_path+.
  #
  # Override to render a different partial:
  #
  #   class User < ApplicationRecord
  #     def to_trix_content_attachment_partial_path
  #       "users/trix_content_attachment"
  #     end
  #   end
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:111
  def to_trix_content_attachment_partial_path; end

  private

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:142
  def attribute_names_for_serialization; end

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:146
  def read_attribute_for_serialization(key); end

  class << self
    # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:41
    def from_attachable_sgid(sgid, options = T.unsafe(nil)); end

    # Extracts the +ActionText::Attachable+ from the attachment HTML node:
    #
    #   person = Person.create! name: "Javan"
    #   html = %Q(<action-text-attachment sgid="#{person.attachable_sgid}"></action-text-attachment>)
    #   fragment = ActionText::Fragment.wrap(html)
    #   attachment_node = fragment.find_all(ActionText::Attachment.tag_name).first
    #   ActionText::Attachable.from_node(attachment_node) # => person
    #
    # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:29
    def from_node(node); end

    private

    # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:48
    def attachable_from_sgid(sgid); end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/attachable.rb:0
module ActionText::Attachable::ClassMethods
  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:56
  def from_attachable_sgid(sgid); end

  # source://actiontext-7.1.5.2/lib/action_text/attachable.rb:70
  def to_missing_attachable_partial_path; end
end

# source://actiontext-7.1.5.2/lib/action_text/attachable.rb:19
ActionText::Attachable::LOCATOR_NAME = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text.rb:30
module ActionText::Attachables
  extend ::ActiveSupport::Autoload
end

# source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:5
class ActionText::Attachables::ContentAttachment
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::ActiveModel::Access
  include ::ActiveModel::Model
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
  def __callbacks; end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
  def __callbacks?; end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:951
  def _run_validate_callbacks(&block); end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:963
  def _validate_callbacks; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
  def _validators; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
  def _validators?; end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:18
  def attachable_plain_text_representation(caption); end

  # Returns the value of attribute content.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:13
  def content; end

  # Sets the attribute content
  #
  # @param value the value to set the attribute content to.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:13
  def content=(_arg0); end

  # Returns the value of attribute content_type.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:13
  def content_type; end

  # Sets the attribute content_type
  #
  # @param value the value to set the attribute content_type to.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:13
  def content_type=(_arg0); end

  # source://activemodel-7.1.5.2/lib/active_model/naming.rb:255
  def model_name(&block); end

  # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
  def param_delimiter=(_arg0); end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:22
  def to_html; end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:30
  def to_partial_path; end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:26
  def to_s; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:67
  def validation_context; end

  private

  # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:35
  def content_instance; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:67
  def validation_context=(_arg0); end

  class << self
    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
    def __callbacks; end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
    def __callbacks=(value); end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
    def __callbacks?; end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:955
    def _validate_callbacks; end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:959
    def _validate_callbacks=(value); end

    # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
    def _validators; end

    # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
    def _validators=(value); end

    # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
    def _validators?; end

    # source://actiontext-7.1.5.2/lib/action_text/attachables/content_attachment.rb:8
    def from_node(node); end

    # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
    def param_delimiter; end

    # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
    def param_delimiter=(value); end

    # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
    def param_delimiter?; end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/attachables/missing_attachable.rb:5
class ActionText::Attachables::MissingAttachable
  extend ::ActiveModel::Naming

  # @return [MissingAttachable] a new instance of MissingAttachable
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/missing_attachable.rb:10
  def initialize(sgid); end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/missing_attachable.rb:22
  def model; end

  # source://activemodel-7.1.5.2/lib/active_model/naming.rb:255
  def model_name(&block); end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/missing_attachable.rb:14
  def to_partial_path; end
end

# source://actiontext-7.1.5.2/lib/action_text/attachables/missing_attachable.rb:8
ActionText::Attachables::MissingAttachable::DEFAULT_PARTIAL_PATH = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:5
class ActionText::Attachables::RemoteImage
  extend ::ActiveModel::Naming

  # @return [RemoteImage] a new instance of RemoteImage
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:30
  def initialize(attributes = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:37
  def attachable_plain_text_representation(caption); end

  # Returns the value of attribute content_type.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:28
  def content_type; end

  # Returns the value of attribute height.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:28
  def height; end

  # source://activemodel-7.1.5.2/lib/active_model/naming.rb:255
  def model_name(&block); end

  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:41
  def to_partial_path; end

  # Returns the value of attribute url.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:28
  def url; end

  # Returns the value of attribute width.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:28
  def width; end

  class << self
    # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:9
    def from_node(node); end

    private

    # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:20
    def attributes_from_node(node); end

    # @return [Boolean]
    #
    # source://actiontext-7.1.5.2/lib/action_text/attachables/remote_image.rb:16
    def content_type_is_image?(content_type); end
  end
end

# = Action Text \Attachment
#
# Attachments serialize attachables to HTML or plain text.
#
#   class Person < ApplicationRecord
#     include ActionText::Attachable
#   end
#
#   attachable = Person.create! name: "Javan"
#   attachment = ActionText::Attachment.from_attachable(attachable)
#   attachment.to_html # => "<action-text-attachment sgid=\"BAh7CEk..."
#
# source://actiontext-7.1.5.2/lib/action_text/attachment.rb:17
class ActionText::Attachment
  include ::ActionText::Attachments::Caching
  include ::ActionText::Attachments::Minification
  include ::ActionText::Attachments::TrixConversion
  extend ::ActionText::Attachments::Minification::ClassMethods
  extend ::ActionText::Attachments::TrixConversion::ClassMethods

  # @return [Attachment] a new instance of Attachment
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:66
  def initialize(node, attachable); end

  # Returns the value of attribute attachable.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:61
  def attachable; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:71
  def caption; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:75
  def full_attributes; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:129
  def inspect; end

  # source://activesupport-7.1.5.2/lib/active_support/core_ext/module/delegation.rb:354
  def method_missing(method, *args, &block); end

  # Returns the value of attribute node.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:61
  def node; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:20
  def tag_name; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:20
  def tag_name=(val); end

  # Converts the attachment to HTML.
  #
  #   attachable = Person.create! name: "Javan"
  #   attachment = ActionText::Attachment.from_attachable(attachable)
  #   attachment.to_html # => "<action-text-attachment sgid=\"BAh7CEk...
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:121
  def to_html; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:63
  def to_param(*_arg0, &_arg1); end

  # Converts the attachment to plain text.
  #
  #   attachable = ActiveStorage::Blob.find_by filename: "racecar.jpg"
  #   attachment = ActionText::Attachment.from_attachable(attachable)
  #   attachment.to_plain_text # => "[racecar.jpg]"
  #
  # Use the +caption+ when set:
  #
  #   attachment = ActionText::Attachment.from_attachable(attachable, caption: "Vroom vroom")
  #   attachment.to_plain_text # => "[Vroom vroom]"
  #
  # The presentation can be overridden by implementing the
  # +attachable_plain_text_representation+ method:
  #
  #   class Person < ApplicationRecord
  #     include ActionText::Attachable
  #
  #     def attachable_plain_text_representation
  #       "[#{name}]"
  #     end
  #   end
  #
  #   attachable = Person.create! name: "Javan"
  #   attachment = ActionText::Attachment.from_attachable(attachable)
  #   attachment.to_plain_text # => "[Javan]"
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:108
  def to_plain_text; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:125
  def to_s; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:79
  def with_full_attributes; end

  private

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:138
  def attachable_attributes; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:134
  def node_attributes; end

  # source://activesupport-7.1.5.2/lib/active_support/core_ext/module/delegation.rb:346
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:142
  def sgid_attributes; end

  class << self
    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:25
    def fragment_by_canonicalizing_attachments(content); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:37
    def from_attachable(attachable, attributes = T.unsafe(nil)); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:33
    def from_attachables(attachables); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:43
    def from_attributes(attributes, attachable = T.unsafe(nil)); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:29
    def from_node(node, attachable = T.unsafe(nil)); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:20
    def tag_name; end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:20
    def tag_name=(val); end

    private

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:50
    def node_from_attributes(attributes); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment.rb:56
    def process_attributes(attributes); end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/attachment.rb:22
ActionText::Attachment::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:4
class ActionText::AttachmentGallery
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::ActiveModel::Access
  include ::ActiveModel::Model
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods

  # @return [AttachmentGallery] a new instance of AttachmentGallery
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:52
  def initialize(node); end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
  def __callbacks; end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
  def __callbacks?; end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:951
  def _run_validate_callbacks(&block); end

  # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:963
  def _validate_callbacks; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
  def _validators; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
  def _validators?; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:56
  def attachments; end

  # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:66
  def inspect; end

  # source://activemodel-7.1.5.2/lib/active_model/naming.rb:255
  def model_name(&block); end

  # Returns the value of attribute node.
  #
  # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:50
  def node; end

  # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
  def param_delimiter=(_arg0); end

  # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:62
  def size; end

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:67
  def validation_context; end

  private

  # source://activemodel-7.1.5.2/lib/active_model/validations.rb:67
  def validation_context=(_arg0); end

  class << self
    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
    def __callbacks; end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
    def __callbacks=(value); end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:70
    def __callbacks?; end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:955
    def _validate_callbacks; end

    # source://activesupport-7.1.5.2/lib/active_support/callbacks.rb:959
    def _validate_callbacks=(value); end

    # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
    def _validators; end

    # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
    def _validators=(value); end

    # source://activemodel-7.1.5.2/lib/active_model/validations.rb:71
    def _validators?; end

    # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:41
    def attachment_selector; end

    # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:25
    def find_attachment_gallery_nodes(content); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:11
    def fragment_by_canonicalizing_attachment_galleries(content); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:17
    def fragment_by_replacing_attachment_gallery_nodes(content); end

    # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:37
    def from_node(node); end

    # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
    def param_delimiter; end

    # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
    def param_delimiter=(value); end

    # source://activemodel-7.1.5.2/lib/active_model/conversion.rb:32
    def param_delimiter?; end

    # source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:45
    def selector; end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/attachment_gallery.rb:7
ActionText::AttachmentGallery::TAG_NAME = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text.rb:38
module ActionText::Attachments
  extend ::ActiveSupport::Autoload
end

# source://actiontext-7.1.5.2/lib/action_text/attachments/caching.rb:5
module ActionText::Attachments::Caching
  # source://actiontext-7.1.5.2/lib/action_text/attachments/caching.rb:6
  def cache_key(*args); end

  private

  # source://actiontext-7.1.5.2/lib/action_text/attachments/caching.rb:11
  def cache_digest; end
end

# source://actiontext-7.1.5.2/lib/action_text/attachments/minification.rb:5
module ActionText::Attachments::Minification
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attachments::Minification::ClassMethods
end

# source://actiontext-7.1.5.2/lib/action_text/attachments/minification.rb:0
module ActionText::Attachments::Minification::ClassMethods
  # source://actiontext-7.1.5.2/lib/action_text/attachments/minification.rb:9
  def fragment_by_minifying_attachments(content); end
end

# source://actiontext-7.1.5.2/lib/action_text/attachments/trix_conversion.rb:7
module ActionText::Attachments::TrixConversion
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attachments::TrixConversion::ClassMethods

  # source://actiontext-7.1.5.2/lib/action_text/attachments/trix_conversion.rb:22
  def to_trix_attachment(content = T.unsafe(nil)); end

  private

  # source://actiontext-7.1.5.2/lib/action_text/attachments/trix_conversion.rb:29
  def trix_attachment_content; end
end

# source://actiontext-7.1.5.2/lib/action_text/attachments/trix_conversion.rb:0
module ActionText::Attachments::TrixConversion::ClassMethods
  # source://actiontext-7.1.5.2/lib/action_text/attachments/trix_conversion.rb:11
  def fragment_by_converting_trix_attachments(content); end

  # source://actiontext-7.1.5.2/lib/action_text/attachments/trix_conversion.rb:17
  def from_trix_attachment(trix_attachment); end
end

# source://actiontext-7.1.5.2/lib/action_text/attribute.rb:4
module ActionText::Attribute
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Attribute::ClassMethods
end

# source://actiontext-7.1.5.2/lib/action_text/attribute.rb:0
module ActionText::Attribute::ClassMethods
  # source://actiontext-7.1.5.2/lib/action_text/attribute.rb:37
  def has_rich_text(name, encrypted: T.unsafe(nil), strict_loading: T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/attribute.rb:66
  def rich_text_association_names; end

  # source://actiontext-7.1.5.2/lib/action_text/attribute.rb:62
  def with_all_rich_text; end
end

# source://actiontext-7.1.5.2/lib/action_text/encryption.rb:4
module ActionText::Encryption
  # source://actiontext-7.1.5.2/lib/action_text/encryption.rb:12
  def decrypt; end

  # source://actiontext-7.1.5.2/lib/action_text/encryption.rb:5
  def encrypt; end

  private

  # source://actiontext-7.1.5.2/lib/action_text/encryption.rb:24
  def decrypt_rich_texts; end

  # source://actiontext-7.1.5.2/lib/action_text/encryption.rb:20
  def encrypt_rich_texts; end

  # source://actiontext-7.1.5.2/lib/action_text/encryption.rb:32
  def encryptable_rich_texts; end

  # @return [Boolean]
  #
  # source://actiontext-7.1.5.2/lib/action_text/encryption.rb:28
  def has_encrypted_rich_texts?; end
end

# source://actiontext-7.1.5.2/lib/action_text/engine.rb:11
class ActionText::Engine < ::Rails::Engine; end

# = Action Text \FixtureSet
#
# Fixtures are a way of organizing data that you want to test against; in
# short, sample data.
#
# To learn more about fixtures, read the ActiveRecord::FixtureSet documentation.
#
# === YAML
#
# Like other Active Record-backed models, ActionText::RichText records inherit
# from ActiveRecord::Base instances and can therefore be populated by
# fixtures.
#
# Consider an <tt>Article</tt> class:
#
#   class Article < ApplicationRecord
#     has_rich_text :content
#   end
#
# To declare fixture data for the related <tt>content</tt>, first declare fixture
# data for <tt>Article</tt> instances in <tt>test/fixtures/articles.yml</tt>:
#
#   first:
#     title: An Article
#
# Then declare the ActionText::RichText fixture data in
# <tt>test/fixtures/action_text/rich_texts.yml</tt>, making sure to declare
# each entry's <tt>record:</tt> key as a polymorphic relationship:
#
#   first:
#     record: first (Article)
#     name: content
#     body: <div>Hello, world.</div>
#
# When processed, Active Record will insert database records for each fixture
# entry and will ensure the Action Text relationship is intact.
#
# source://actiontext-7.1.5.2/lib/action_text/fixture_set.rb:40
class ActionText::FixtureSet
  class << self
    # Fixtures support Action Text attachments as part of their <tt>body</tt>
    # HTML.
    #
    # === Examples
    #
    # For example, consider a second <tt>Article</tt> fixture declared in
    # <tt>test/fixtures/articles.yml</tt>:
    #
    #   second:
    #     title: Another Article
    #
    # You can attach a mention of <tt>articles(:first)</tt> to <tt>second</tt>'s
    # <tt>content</tt> by embedding a call to <tt>ActionText::FixtureSet.attachment</tt>
    # in the <tt>body:</tt> value in <tt>test/fixtures/action_text/rich_texts.yml</tt>:
    #
    #   second:
    #     record: second (Article)
    #     name: content
    #     body: <div>Hello, <%= ActionText::FixtureSet.attachment("articles", :first) %></div>
    #
    # source://actiontext-7.1.5.2/lib/action_text/fixture_set.rb:61
    def attachment(fixture_set_name, label, column_type: T.unsafe(nil)); end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/fragment.rb:4
class ActionText::Fragment
  # @return [Fragment] a new instance of Fragment
  #
  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:24
  def initialize(source); end

  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:28
  def find_all(selector); end

  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:37
  def replace(selector); end

  # Returns the value of attribute source.
  #
  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:22
  def source; end

  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:50
  def to_html; end

  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:46
  def to_plain_text; end

  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:54
  def to_s; end

  # @yield [source = self.source.dup]
  #
  # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:32
  def update; end

  class << self
    # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:17
    def from_html(html); end

    # source://actiontext-7.1.5.2/lib/action_text/fragment.rb:6
    def wrap(fragment_or_html); end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/html_conversion.rb:4
module ActionText::HtmlConversion
  extend ::ActionText::HtmlConversion

  # source://actiontext-7.1.5.2/lib/action_text/html_conversion.rb:15
  def create_element(tag_name, attributes = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/html_conversion.rb:11
  def fragment_for_html(html); end

  # source://actiontext-7.1.5.2/lib/action_text/html_conversion.rb:7
  def node_to_html(node); end

  private

  # source://actiontext-7.1.5.2/lib/action_text/html_conversion.rb:20
  def document; end
end

# source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:4
module ActionText::PlainTextConversion
  extend ::ActionText::PlainTextConversion

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:7
  def node_to_plain_text(node); end

  private

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:109
  def break_if_nested_list(node, text); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:86
  def bullet_for_li_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:98
  def indentation_for_li_node(node); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:105
  def list_node_depth_for_node(node); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:94
  def list_node_name_for_li_node(node); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:32
  def plain_text_for_block(node, index = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:64
  def plain_text_for_blockquote_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:48
  def plain_text_for_br_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:56
  def plain_text_for_div_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:60
  def plain_text_for_figcaption_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:32
  def plain_text_for_h1_node(node, index = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:74
  def plain_text_for_li_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:40
  def plain_text_for_list(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:12
  def plain_text_for_node(node, index = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:20
  def plain_text_for_node_children(node); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:40
  def plain_text_for_ol_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:32
  def plain_text_for_p_node(node, index = T.unsafe(nil)); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:52
  def plain_text_for_text_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:40
  def plain_text_for_ul_node(node, index); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:28
  def plain_text_method_for_node(node); end

  # source://actiontext-7.1.5.2/lib/action_text/plain_text_conversion.rb:82
  def remove_trailing_newlines(text); end
end

# source://actiontext-7.1.5.2/lib/action_text/rendering.rb:7
module ActionText::Rendering
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Rendering::ClassMethods
end

# source://actiontext-7.1.5.2/lib/action_text/rendering.rb:0
module ActionText::Rendering::ClassMethods
  # source://actiontext-7.1.5.2/lib/action_text/rendering.rb:16
  def action_controller_renderer; end

  # source://actiontext-7.1.5.2/lib/action_text/rendering.rb:28
  def render(*args, &block); end

  # source://actiontext-7.1.5.2/lib/action_text/rendering.rb:20
  def with_renderer(renderer); end
end

# source://actiontext-7.1.5.2/lib/action_text/serialization.rb:4
module ActionText::Serialization
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActionText::Serialization::ClassMethods

  # source://actiontext-7.1.5.2/lib/action_text/serialization.rb:32
  def _dump(*_arg0); end
end

# source://actiontext-7.1.5.2/lib/action_text/serialization.rb:0
module ActionText::Serialization::ClassMethods
  # source://actiontext-7.1.5.2/lib/action_text/serialization.rb:8
  def _load(content); end

  # source://actiontext-7.1.5.2/lib/action_text/serialization.rb:12
  def dump(content); end

  # source://actiontext-7.1.5.2/lib/action_text/serialization.rb:8
  def load(content); end
end

# source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:4
class ActionText::TrixAttachment
  # @return [TrixAttachment] a new instance of TrixAttachment
  #
  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:51
  def initialize(node); end

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:55
  def attributes; end

  # Returns the value of attribute node.
  #
  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:49
  def node; end

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:59
  def to_html; end

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:63
  def to_s; end

  private

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:68
  def attachment_attributes; end

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:72
  def composed_attributes; end

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:80
  def read_json_attribute(name); end

  # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:76
  def read_json_object_attribute(name); end

  class << self
    # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:19
    def from_attributes(attributes); end

    private

    # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:33
    def process_attributes(attributes); end

    # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:37
    def transform_attribute_keys(attributes); end

    # source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:41
    def typecast_attribute_values(attributes); end
  end
end

# source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:9
ActionText::TrixAttachment::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:10
ActionText::TrixAttachment::ATTRIBUTE_TYPES = T.let(T.unsafe(nil), Hash)

# source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:8
ActionText::TrixAttachment::COMPOSED_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:6
ActionText::TrixAttachment::SELECTOR = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text/trix_attachment.rb:5
ActionText::TrixAttachment::TAG_NAME = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:9
module ActionText::VERSION; end

# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:10
ActionText::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:11
ActionText::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:13
ActionText::VERSION::PRE = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:15
ActionText::VERSION::STRING = T.let(T.unsafe(nil), String)

# source://actiontext-7.1.5.2/lib/action_text/gem_version.rb:12
ActionText::VERSION::TINY = T.let(T.unsafe(nil), Integer)
