# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bootstrap-sass` gem.
# Please instead update this file by running `bin/tapioca gem bootstrap-sass`.

# source://bootstrap-sass-3.4.1/lib/bootstrap-sass/version.rb:1
module Bootstrap
  class << self
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:42
    def assets_path; end

    # @return [Boolean]
    #
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:51
    def compass?; end

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:34
    def fonts_path; end

    # Paths
    #
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:26
    def gem_path; end

    # @return [Boolean]
    #
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:59
    def hanami?; end

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:38
    def javascripts_path; end

    # Inspired by Kaminari
    #
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:5
    def load!; end

    # @return [Boolean]
    #
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:55
    def rails?; end

    # Environment detection helpers
    #
    # @return [Boolean]
    #
    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:47
    def sprockets?; end

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:30
    def stylesheets_path; end

    private

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:65
    def register_compass_extension; end

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:79
    def register_hanami; end

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:75
    def register_rails_engine; end

    # source://bootstrap-sass-3.4.1/lib/bootstrap-sass.rb:83
    def register_sprockets; end
  end
end

# source://bootstrap-sass-3.4.1/lib/bootstrap-sass/version.rb:3
Bootstrap::BOOTSTRAP_SHA = T.let(T.unsafe(nil), String)

# source://bootstrap-sass-3.4.1/lib/bootstrap-sass/engine.rb:2
module Bootstrap::Rails; end

# source://bootstrap-sass-3.4.1/lib/bootstrap-sass/engine.rb:3
class Bootstrap::Rails::Engine < ::Rails::Engine; end

# source://bootstrap-sass-3.4.1/lib/bootstrap-sass/version.rb:2
Bootstrap::VERSION = T.let(T.unsafe(nil), String)
