# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `d3-rails` gem.
# Please instead update this file by running `bin/tapioca gem d3-rails`.

# source://d3-rails-3.5.17/lib/d3/rails/engine.rb:1
module D3; end

# source://d3-rails-3.5.17/lib/d3/rails/engine.rb:2
module D3::Rails; end

# source://d3-rails-3.5.17/lib/d3/rails/engine.rb:3
class D3::Rails::Engine < ::Rails::Engine; end

# source://d3-rails-3.5.17/lib/d3/rails/version.rb:3
D3::Rails::VERSION = T.let(T.unsafe(nil), String)
