# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `elasticsearch-transport` gem.
# Please instead update this file by running `bin/tapioca gem elasticsearch-transport`.

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:5
module Elasticsearch; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport.rb:27
module Elasticsearch::Client
  extend ::Elasticsearch::Client

  # A convenience wrapper for {::Elasticsearch::Transport::Client#initialize}.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport.rb:31
  def new(arguments = T.unsafe(nil), &block); end
end

# Module to encapsulate all logging functionality.
#
# @since 7.0.0
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:10
module Elasticsearch::Loggable
  # Log a debug message.
  #
  # @example Log a debug message.
  #   log_debug('Message')
  # @param message [String] The message to log.
  # @since 7.0.0
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:20
  def log_debug(message); end

  # Log an error message.
  #
  # @example Log an error message.
  #   log_error('Message')
  # @param message [String] The message to log.
  # @since 7.0.0
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:32
  def log_error(message); end

  # Log a fatal message.
  #
  # @example Log a fatal message.
  #   log_fatal('Message')
  # @param message [String] The message to log.
  # @since 7.0.0
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:44
  def log_fatal(message); end

  # Log an info message.
  #
  # @example Log an info message.
  #   log_info('Message')
  # @param message [String] The message to log.
  # @since 7.0.0
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:56
  def log_info(message); end

  # Log a warn message.
  #
  # @example Log a warn message.
  #   log_warn('Message')
  # @param message [String] The message to log.
  # @since 7.0.0
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/loggable.rb:68
  def log_warn(message); end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:6
module Elasticsearch::Transport; end

# Handles communication with an Elasticsearch cluster.
#
# See {file:README.md README} for usage and code examples.
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:14
class Elasticsearch::Transport::Client
  # Create a client connected to an Elasticsearch cluster.
  #
  # Specify the URL via arguments or set the `ELASTICSEARCH_URL` environment variable.
  #
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @option arguments
  # @param arguments [Hash] a customizable set of options
  # @return [Client] a new instance of Client
  # @yield [faraday] Access and configure the `Faraday::Connection` instance directly with a block
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:104
  def initialize(arguments = T.unsafe(nil), &block); end

  # Performs a request through delegation to {#transport}.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:150
  def perform_request(method, path, params = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil)); end

  # Returns the transport object.
  #
  # @see Elasticsearch::Transport::Transport::Base
  # @see Elasticsearch::Transport::Transport::HTTP::Faraday
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:48
  def transport; end

  # Returns the transport object.
  #
  # @see Elasticsearch::Transport::Transport::Base
  # @see Elasticsearch::Transport::Transport::HTTP::Faraday
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:48
  def transport=(_arg0); end

  private

  # Auto-detect the best adapter (HTTP "driver") available, based on libraries
  # loaded by the user, preferring those with persistent connections
  # ("keep-alive") by default
  #
  # @api private
  # @return [Symbol]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:244
  def __auto_detect_adapter; end

  # Normalizes and returns hosts configuration.
  #
  # Arrayifies the `hosts_config` argument and extracts `host` and `port` info from strings.
  # Performs shuffling when the `randomize_hosts` option is set.
  #
  # TODO: Refactor, so it's available in Elasticsearch::Transport::Base as well
  #
  # @api private
  # @raise [ArgumentError]
  # @return [Array<Hash>]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:180
  def __extract_hosts(hosts_config); end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:196
  def __parse_host(host); end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:157
  def extract_cloud_creds(arguments); end
end

# The default port to use if connecting using a Cloud ID.
#
# @since 7.2.0
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:41
Elasticsearch::Transport::Client::DEFAULT_CLOUD_PORT = T.let(T.unsafe(nil), Integer)

# The default host and port to use if not otherwise specified.
#
# @since 7.0.0
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:36
Elasticsearch::Transport::Client::DEFAULT_HOST = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:17
Elasticsearch::Transport::Client::DEFAULT_LOGGER = T.let(T.unsafe(nil), Proc)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:25
Elasticsearch::Transport::Client::DEFAULT_TRACER = T.let(T.unsafe(nil), Proc)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:15
Elasticsearch::Transport::Client::DEFAULT_TRANSPORT_CLASS = Elasticsearch::Transport::Transport::HTTP::Faraday

# Class for wrapping a hash that could have sensitive data.
# When printed, the sensitive values will be redacted.
#
# @since 6.1.1
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:12
class Elasticsearch::Transport::Redacted < ::Hash
  # @return [Redacted] a new instance of Redacted
  # @since 6.1.1
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:14
  def initialize(elements = T.unsafe(nil)); end

  # Get a string representation of the hash.
  #
  # @return [String] The string representation of the hash.
  # @since 6.1.1
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:35
  def inspect; end

  # Get a string representation of the hash.
  #
  # @return [String] The string representation of the hash.
  # @since 6.1.1
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:44
  def to_s; end

  private

  # @since 6.1.1
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:56
  def redact(k, v, method); end

  # @since 6.1.1
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:50
  def redacted_string(method); end
end

# The keys whose values will be redacted.
#
# @since 6.1.1
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:22
Elasticsearch::Transport::Redacted::SENSITIVE_KEYS = T.let(T.unsafe(nil), Array)

# The replacement string used in place of the value for sensitive keys.
#
# @since 6.1.1
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/redacted.rb:28
Elasticsearch::Transport::Redacted::STRING_REPLACEMENT = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:7
module Elasticsearch::Transport::Transport; end

# @abstract Module with common functionality for transport implementations.
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:11
module Elasticsearch::Transport::Transport::Base
  include ::Elasticsearch::Loggable

  # Creates a new transport object
  #
  # @option arguments
  # @option arguments
  # @param arguments [Hash] Settings and options for the transport
  # @param block [Proc] Lambda or Proc which can be evaluated in the context of the "session" object
  # @see Client#initialize
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:37
  def initialize(arguments = T.unsafe(nil), &block); end

  # @abstract Build and return a connection.
  #   A transport implementation *must* implement this method.
  #   See {HTTP::Faraday#__build_connection} for an example.
  # @api private
  # @raise [NoMethodError]
  # @return [Connections::Connection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:157
  def __build_connection(host, options = T.unsafe(nil), block = T.unsafe(nil)); end

  # Builds and returns a collection of connections
  #
  # The adapters have to implement the {Base#__build_connection} method.
  #
  # @api private
  # @return [Connections::Collection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:134
  def __build_connections; end

  # Closes the connections collection
  #
  # @api private
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:165
  def __close_connections; end

  # Converts any non-String object to JSON
  #
  # @api private
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:212
  def __convert_to_json(o = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns a full URL based on information from host
  #
  # @api private
  # @param host [Hash] Host configuration passed in from {Client}
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:221
  def __full_url(host); end

  # Log request and response information
  #
  # @api private
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:173
  def __log_response(method, path, params, body, url, response, json, took, duration); end

  # Raise error specific for the HTTP response status or a generic server error
  #
  # @api private
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:203
  def __raise_transport_error(response); end

  # Rebuilds the connections collection in the transport.
  #
  # The methods *adds* new connections from the passed hosts to the collection,
  # and *removes* all connections not contained in the passed hosts.
  #
  # @api private
  # @return [Connections::Collection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:110
  def __rebuild_connections(arguments = T.unsafe(nil)); end

  # Trace the request in the `curl` format
  #
  # @api private
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:187
  def __trace(method, path, params, headers, body, url, response, json, took, duration); end

  # Returns the value of attribute connections.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:22
  def connections; end

  # Returns the value of attribute counter.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:22
  def counter; end

  # Returns a connection from the connection pool by delegating to {Connections::Collection#get_connection}.
  #
  # Resurrects dead connection if the `resurrect_after` timeout has passed.
  # Increments the counter and performs connection reloading if the `reload_connections` option is set.
  #
  # @return [Connections::Connection]
  # @see Connections::Collection#get_connection
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:73
  def get_connection(options = T.unsafe(nil)); end

  # @abstract Returns an Array of connection errors specific to the transport implementation.
  #   See {HTTP::Faraday#host_unreachable_exceptions} for an example.
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:355
  def host_unreachable_exceptions; end

  # Returns the value of attribute hosts.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:22
  def hosts; end

  # Returns the value of attribute last_request_at.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:22
  def last_request_at; end

  # Returns the value of attribute logger.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def logger; end

  # Sets the attribute logger
  #
  # @param value the value to set the attribute logger to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def logger=(_arg0); end

  # Returns the value of attribute options.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:22
  def options; end

  # Performs a request to Elasticsearch, while handling logging, tracing, marking dead connections,
  # retrying the request and reloading the connections.
  #
  # @abstract The transport implementation has to implement this method either in full,
  #   or by invoking this method with a block. See {HTTP::Faraday#perform_request} for an example.
  # @param method [String] Request method
  # @param path [String] The API endpoint
  # @param params [Hash] Request parameters (will be serialized by {Connections::Connection#full_url})
  # @param body [Hash] Request body (will be serialized by the {#serializer})
  # @param headers [Hash] Request headers (will be serialized by the {#serializer})
  # @param block [Proc] Code block to evaluate, passed from the implementation
  # @raise [NoMethodError] If no block is passed
  # @raise [ServerError] If request failed on server
  # @raise [Error] If no connection is available
  # @return [Response]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:248
  def perform_request(method, path, params = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), opts = T.unsafe(nil), &block); end

  # Returns the value of attribute protocol.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:22
  def protocol; end

  # Returns the value of attribute reload_after.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def reload_after; end

  # Sets the attribute reload_after
  #
  # @param value the value to set the attribute reload_after to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def reload_after=(_arg0); end

  # Returns the value of attribute reload_connections.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def reload_connections; end

  # Reloads and replaces the connection collection based on cluster information
  #
  # @see Sniffer#hosts
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:85
  def reload_connections!; end

  # Sets the attribute reload_connections
  #
  # @param value the value to set the attribute reload_connections to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def reload_connections=(_arg0); end

  # Returns the value of attribute resurrect_after.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def resurrect_after; end

  # Sets the attribute resurrect_after
  #
  # @param value the value to set the attribute resurrect_after to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def resurrect_after=(_arg0); end

  # Tries to "resurrect" all eligible dead connections
  #
  # @see Connections::Connection#resurrect!
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:98
  def resurrect_dead_connections!; end

  # Returns the value of attribute serializer.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def serializer; end

  # Sets the attribute serializer
  #
  # @param value the value to set the attribute serializer to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def serializer=(_arg0); end

  # Returns the value of attribute sniffer.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def sniffer; end

  # Sets the attribute sniffer
  #
  # @param value the value to set the attribute sniffer to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def sniffer=(_arg0); end

  # Returns the value of attribute tracer.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def tracer; end

  # Sets the attribute tracer
  #
  # @param value the value to set the attribute tracer to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:23
  def tracer=(_arg0); end

  private

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:393
  def apply_headers(client, options); end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:372
  def decompress_response(body); end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:401
  def find_value(hash, regex); end

  # @return [Boolean]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:385
  def gzipped?(body); end

  # @return [Boolean]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:389
  def use_compression?; end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:409
  def user_agent_header(client); end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:367
Elasticsearch::Transport::Transport::Base::ACCEPT_ENCODING = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:364
Elasticsearch::Transport::Transport::Base::CONTENT_TYPE_REGEX = T.let(T.unsafe(nil), Regexp)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:363
Elasticsearch::Transport::Transport::Base::CONTENT_TYPE_STR = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:365
Elasticsearch::Transport::Transport::Base::DEFAULT_CONTENT_TYPE = T.let(T.unsafe(nil), String)

# Requests
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:18
Elasticsearch::Transport::Transport::Base::DEFAULT_MAX_RETRIES = T.let(T.unsafe(nil), Integer)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:14
Elasticsearch::Transport::Transport::Base::DEFAULT_PORT = T.let(T.unsafe(nil), Integer)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:15
Elasticsearch::Transport::Transport::Base::DEFAULT_PROTOCOL = T.let(T.unsafe(nil), String)

# Requests
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:16
Elasticsearch::Transport::Transport::Base::DEFAULT_RELOAD_AFTER = T.let(T.unsafe(nil), Integer)

# Seconds
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:17
Elasticsearch::Transport::Transport::Base::DEFAULT_RESURRECT_AFTER = T.let(T.unsafe(nil), Integer)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:19
Elasticsearch::Transport::Transport::Base::DEFAULT_SERIALIZER_CLASS = Elasticsearch::Transport::Transport::Serializer::MultiJson

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:366
Elasticsearch::Transport::Transport::Base::GZIP = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:368
Elasticsearch::Transport::Transport::Base::GZIP_FIRST_TWO_BYTES = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:369
Elasticsearch::Transport::Transport::Base::HEX_STRING_DIRECTIVE = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:370
Elasticsearch::Transport::Transport::Base::RUBY_ENCODING = T.let(T.unsafe(nil), TrueClass)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:20
Elasticsearch::Transport::Transport::Base::SANITIZED_PASSWORD = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:362
Elasticsearch::Transport::Transport::Base::USER_AGENT_REGEX = T.let(T.unsafe(nil), Regexp)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:361
Elasticsearch::Transport::Transport::Base::USER_AGENT_STR = T.let(T.unsafe(nil), String)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:8
module Elasticsearch::Transport::Transport::Connections; end

# Wraps the collection of connections for the transport object as an Enumerable object.
#
# @see Base#connections
# @see Selector::Base#select
# @see Connection
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:16
class Elasticsearch::Transport::Transport::Connections::Collection
  include ::Enumerable

  # @option arguments
  # @option arguments
  # @option arguments
  # @param arguments [Hash] a customizable set of options
  # @return [Collection] a new instance of Collection
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:27
  def initialize(arguments = T.unsafe(nil)); end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:84
  def [](*args); end

  # Add connection(s) to the collection
  #
  # @param connections [Connection, Array] A connection or an array of connections to add
  # @return [self]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:98
  def add(connections); end

  # Returns an Array of alive connections.
  #
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:45
  def alive; end

  # Returns an Array of all connections, both dead and alive
  #
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:62
  def all; end

  # Returns an Array of alive connections.
  #
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:45
  def connections; end

  # Returns an Array of dead connections.
  #
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:54
  def dead; end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:80
  def each(&block); end

  # Returns a connection.
  #
  # If there are no alive connections, resurrects a connection with least failures.
  # Delegates to selector's `#select` method to get the connection.
  #
  # @return [Connection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:73
  def get_connection(options = T.unsafe(nil)); end

  # Returns an Array of hosts information in this collection as Hashes.
  #
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:37
  def hosts; end

  # Remove connection(s) from the collection
  #
  # @param connections [Connection, Array] A connection or an array of connections to remove
  # @return [self]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:108
  def remove(connections); end

  # Returns the value of attribute selector.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:21
  def selector; end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:89
  def size; end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:84
  def slice(*args); end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/collection.rb:19
Elasticsearch::Transport::Transport::Connections::Collection::DEFAULT_SELECTOR = Elasticsearch::Transport::Transport::Connections::Selector::RoundRobin

# Wraps the connection information and logic.
#
# The Connection instance wraps the host information (hostname, port, attributes, etc),
# as well as the "session" (a transport client object, such as a {HTTP::Faraday} instance).
#
# It provides methods to construct and properly encode the URLs and paths for passing them
# to the transport client object.
#
# It provides methods to handle connection livecycle (dead, alive, healthy).
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:20
class Elasticsearch::Transport::Transport::Connections::Connection
  # @option arguments
  # @option arguments
  # @option arguments
  # @param arguments [Hash] a customizable set of options
  # @return [Connection] a new instance of Connection
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:29
  def initialize(arguments = T.unsafe(nil)); end

  # Equality operator based on connection protocol, host and port
  #
  # @return [Boolean]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:129
  def ==(other); end

  # Marks this connection as alive, ie. it is eligible to be returned from the pool by the selector.
  #
  # @return [self]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:86
  def alive!; end

  # Returns the value of attribute connection.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:23
  def connection; end

  # Marks this connection as dead, incrementing the `failures` counter and
  # storing the current time as `dead_since`.
  #
  # @return [self]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:73
  def dead!; end

  # Returns true when this connection has been marked dead, false otherwise.
  #
  # @return [Boolean]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:64
  def dead?; end

  # Returns the value of attribute dead_since.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:23
  def dead_since; end

  # Returns the value of attribute failures.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:23
  def failures; end

  # Returns the complete endpoint path with serialized parameters.
  #
  # @return [String]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:56
  def full_path(path, params = T.unsafe(nil)); end

  # Returns the complete endpoint URL with host, port, path and serialized parameters.
  #
  # @return [String]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:44
  def full_url(path, params = T.unsafe(nil)); end

  # Marks this connection as healthy, ie. a request has been successfully performed with it.
  #
  # @return [self]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:97
  def healthy!; end

  # Returns the value of attribute host.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:23
  def host; end

  # Returns the value of attribute options.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:23
  def options; end

  # Marks this connection as alive, if the required timeout has passed.
  #
  # @return [self, nil]
  # @see DEFAULT_RESURRECT_TIMEOUT
  # @see #resurrectable?
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:111
  def resurrect!; end

  # Returns true if the connection is eligible to be resurrected as alive, false otherwise.
  #
  # @return [Boolean]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:119
  def resurrectable?; end

  # @return [String]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:137
  def to_s; end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/connection.rb:21
Elasticsearch::Transport::Transport::Connections::Connection::DEFAULT_RESURRECT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:9
module Elasticsearch::Transport::Transport::Connections::Selector; end

# @abstract Common functionality for connection selector implementations.
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:13
module Elasticsearch::Transport::Transport::Connections::Selector::Base
  # @option arguments
  # @param arguments [Hash] a customizable set of options
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:18
  def initialize(arguments = T.unsafe(nil)); end

  # Returns the value of attribute connections.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:14
  def connections; end

  # @abstract Selector strategies implement this method to
  #   select and return a connection from the pool.
  # @raise [NoMethodError]
  # @return [Connection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:27
  def select(options = T.unsafe(nil)); end
end

# "Random connection" selector strategy.
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:34
class Elasticsearch::Transport::Transport::Connections::Selector::Random
  include ::Elasticsearch::Transport::Transport::Connections::Selector::Base

  # Returns a random connection from the collection.
  #
  # @return [Connections::Connection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:41
  def select(options = T.unsafe(nil)); end
end

# "Round-robin" selector strategy (default).
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:48
class Elasticsearch::Transport::Transport::Connections::Selector::RoundRobin
  include ::Elasticsearch::Transport::Transport::Connections::Selector::Base

  # @option arguments
  # @param arguments [Hash] a customizable set of options
  # @return [RoundRobin] a new instance of RoundRobin
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:53
  def initialize(arguments = T.unsafe(nil)); end

  # Returns the next connection from the collection, rotating them in round-robin fashion.
  #
  # @return [Connections::Connection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/connections/selector.rb:63
  def select(options = T.unsafe(nil)); end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:69
Elasticsearch::Transport::Transport::ERRORS = T.let(T.unsafe(nil), Hash)

# Generic client error
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:11
class Elasticsearch::Transport::Transport::Error < ::StandardError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:21
module Elasticsearch::Transport::Transport::Errors; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::BadGateway < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::BadRequest < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::BlockedByWindowsParentalControls < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::ClientClosedRequest < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::Conflict < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::ExpectationFailed < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::Forbidden < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::Found < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::GatewayTimeout < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::Gone < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::HTTPToHTTPS < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::HTTPVersionNotSupported < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::ImATeapot < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::InternalServerError < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::LengthRequired < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::MethodNotAllowed < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::MovedPermanently < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::MultipleChoices < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::NotAcceptable < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::NotExtended < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::NotFound < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::NotImplemented < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::NotModified < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::PaymentRequired < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::PermanentRedirect < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::PreconditionFailed < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::ProxyAuthenticationRequired < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::RequestEntityTooLarge < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::RequestHeaderTooLarge < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::RequestTimeout < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::RequestURITooLong < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::RequestedRangeNotSatisfiable < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::SeeOther < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::ServiceUnavailable < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::TemporaryRedirect < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::TooManyConnectionsFromThisIP < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::Unauthorized < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::UnsupportedMediaType < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::UpgradeRequired < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::UseProxy < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:71
class Elasticsearch::Transport::Transport::Errors::VariantAlsoNegotiates < ::Elasticsearch::Transport::Transport::ServerError; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:8
module Elasticsearch::Transport::Transport::HTTP; end

# The default transport implementation, using the [_Faraday_](https://rubygems.org/gems/faraday)
# library for abstracting the HTTP client.
#
# @see Transport::Base
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:15
class Elasticsearch::Transport::Transport::HTTP::Faraday
  include ::Elasticsearch::Loggable
  include ::Elasticsearch::Transport::Transport::Base

  # Builds and returns a connection
  #
  # @return [Connections::Connection]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:40
  def __build_connection(host, options = T.unsafe(nil), block = T.unsafe(nil)); end

  # Returns an array of implementation specific connection errors.
  #
  # @return [Array]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:50
  def host_unreachable_exceptions; end

  # Performs the request by invoking {Transport::Base#perform_request} with a block.
  #
  # @return [Response]
  # @see Transport::Base#perform_request
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:23
  def perform_request(method, path, params = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), opts = T.unsafe(nil)); end

  private

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:56
  def user_agent_header(client); end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:23
Elasticsearch::Transport::Transport::HTTP_STATUSES = T.let(T.unsafe(nil), Hash)

# Wraps the response from Elasticsearch.
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/response.rb:11
class Elasticsearch::Transport::Transport::Response
  # @param status [Integer] Response status code
  # @param body [String] Response body
  # @param headers [Hash] Response headers
  # @return [Response] a new instance of Response
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/response.rb:17
  def initialize(status, body, headers = T.unsafe(nil)); end

  # Returns the value of attribute body.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/response.rb:12
  def body; end

  # Returns the value of attribute headers.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/response.rb:12
  def headers; end

  # Returns the value of attribute status.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/response.rb:12
  def status; end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:8
module Elasticsearch::Transport::Transport::Serializer; end

# An abstract class for implementing serializer implementations
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:12
module Elasticsearch::Transport::Transport::Serializer::Base
  # @param transport [Object] The instance of transport which uses this serializer
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:15
  def initialize(transport = T.unsafe(nil)); end
end

# A default JSON serializer (using [MultiJSON](http://rubygems.org/gems/multi_json))
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:22
class Elasticsearch::Transport::Transport::Serializer::MultiJson
  include ::Elasticsearch::Transport::Transport::Serializer::Base

  # Serialize a Hash to JSON string
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:33
  def dump(object, options = T.unsafe(nil)); end

  # De-serialize a Hash from JSON string
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/serializer/multi_json.rb:27
  def load(string, options = T.unsafe(nil)); end
end

# Elasticsearch server error (HTTP status 5xx)
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:19
class Elasticsearch::Transport::Transport::ServerError < ::Elasticsearch::Transport::Transport::Error; end

# Handles node discovery ("sniffing")
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:11
class Elasticsearch::Transport::Transport::Sniffer
  # @param transport [Object] A transport instance
  # @return [Sniffer] a new instance of Sniffer
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:19
  def initialize(transport); end

  # Retrieves the node list from the Elasticsearch's
  # [_Nodes Info API_](https://www.elastic.co/guide/reference/api/admin-cluster-nodes-info/)
  # and returns a normalized Array of information suitable for passing to transport.
  #
  # Shuffles the collection before returning it when the `randomize_hosts` option is set for transport.
  #
  # @raise [SnifferTimeoutError]
  # @return [Array<Hash>]
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:33
  def hosts; end

  # Returns the value of attribute timeout.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:15
  def timeout; end

  # Sets the attribute timeout
  #
  # @param value the value to set the attribute timeout to.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:15
  def timeout=(_arg0); end

  # Returns the value of attribute transport.
  #
  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:14
  def transport; end

  private

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:69
  def parse_address_port(publish_address); end

  # source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:59
  def parse_publish_address(publish_address); end
end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/sniffer.rb:12
Elasticsearch::Transport::Transport::Sniffer::PROTOCOL = T.let(T.unsafe(nil), String)

# Reloading connections timeout (1 sec by default)
#
# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/errors.rb:15
class Elasticsearch::Transport::Transport::SnifferTimeoutError < ::Timeout::Error; end

# source://elasticsearch-transport-7.4.0/lib/elasticsearch/transport/version.rb:7
Elasticsearch::Transport::VERSION = T.let(T.unsafe(nil), String)

# source://elasticsearch-7.4.0/lib/elasticsearch/version.rb:6
Elasticsearch::VERSION = T.let(T.unsafe(nil), String)
