# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `html2haml` gem.
# Please instead update this file by running `bin/tapioca gem html2haml`.

# @private
# @see Nokogiri
class Nokogiri::XML::Comment < ::Nokogiri::XML::CharacterData
  class << self
    def new(*_arg0); end
  end
end

# @private
# @see Nokogiri
class Nokogiri::XML::Element < ::Nokogiri::XML::Node; end
