# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `jquery-rails` gem.
# Please instead update this file by running `bin/tapioca gem jquery-rails`.

# source://jquery-rails-4.6.0/lib/jquery/rails/engine.rb:1
module Jquery; end

# source://jquery-rails-4.6.0/lib/jquery/rails/engine.rb:2
module Jquery::Rails; end

# source://jquery-rails-4.6.0/lib/jquery/rails/engine.rb:3
class Jquery::Rails::Engine < ::Rails::Engine; end

# source://jquery-rails-4.6.0/lib/jquery/rails/version.rb:5
Jquery::Rails::JQUERY_2_VERSION = T.let(T.unsafe(nil), String)

# source://jquery-rails-4.6.0/lib/jquery/rails/version.rb:6
Jquery::Rails::JQUERY_3_VERSION = T.let(T.unsafe(nil), String)

# source://jquery-rails-4.6.0/lib/jquery/rails/version.rb:7
Jquery::Rails::JQUERY_UJS_VERSION = T.let(T.unsafe(nil), String)

# source://jquery-rails-4.6.0/lib/jquery/rails/version.rb:4
Jquery::Rails::JQUERY_VERSION = T.let(T.unsafe(nil), String)

# source://jquery-rails-4.6.0/lib/jquery/rails/version.rb:3
Jquery::Rails::VERSION = T.let(T.unsafe(nil), String)
