# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `multiblock` gem.
# Please instead update this file by running `bin/tapioca gem multiblock`.

# source://multiblock-0.2.1/lib/multiblock/version.rb:1
module Multiblock
  class << self
    # source://multiblock-0.2.1/lib/multiblock.rb:22
    def wrapper(*args, &blk); end
  end
end

# source://multiblock-0.2.1/lib/multiblock.rb:5
Multiblock::BasicObject = BasicObject

# source://multiblock-0.2.1/lib/multiblock/version.rb:2
Multiblock::VERSION = T.let(T.unsafe(nil), String)

# source://multiblock-0.2.1/lib/multiblock/wrapper.rb:2
class Multiblock::Wrapper < ::BasicObject
  # @return [Wrapper] a new instance of Wrapper
  #
  # source://multiblock-0.2.1/lib/multiblock/wrapper.rb:3
  def initialize(&default); end

  # source://multiblock-0.2.1/lib/multiblock/wrapper.rb:14
  def call(name, *args); end

  # source://multiblock-0.2.1/lib/multiblock/wrapper.rb:18
  def inspect; end

  # source://multiblock-0.2.1/lib/multiblock/wrapper.rb:9
  def method_missing(name, *args, &blk); end
end
