# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-ssh` gem.
# Please instead update this file by running `bin/tapioca gem net-ssh`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca/wiki/Manual-Gem-Requires
