# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `snaky_hash` gem.
# Please instead update this file by running `bin/tapioca gem snaky_hash`.

# This is a module-class hybrid.
#
# A flexible key conversion system that supports both String and Symbol keys,
# with optional serialization capabilities.
#
# Hashie's standard SymbolizeKeys is similar to the functionality we want.
# ... but not quite.  We need to support both String (for oauth2) and Symbol keys (for oauth).
# see: Hashie::Extensions::Mash::SymbolizeKeys
#
# @example Basic usage with string keys
#   class MyHash < Hashie::Mash
#   include SnakyHash::Snake.new(key_type: :string)
#   end
# @example Usage with symbol keys and serialization
#   class MySerializableHash < Hashie::Mash
#   include SnakyHash::Snake.new(key_type: :symbol, serializer: true)
#   end
#
# source://snaky_hash-2.0.7/lib/snaky_hash/version.rb:3
module SnakyHash; end

# Base error class for all SnakyHash errors
#
# @api public
#
# source://snaky_hash-2.0.7/lib/snaky_hash.rb:33
class SnakyHash::Error < ::StandardError; end

# Manages extensions that can modify values in a chain of transformations
#
# @example Adding and running an extension
#   extensions = Extensions.new
#   extensions.add(:upcase) { |value| value.to_s.upcase }
#   extensions.run("hello") #=> "HELLO"
#
# source://snaky_hash-2.0.7/lib/snaky_hash/extensions.rb:11
class SnakyHash::Extensions
  # Initializes a new Extensions instance with an empty extensions registry
  #
  # @return [Extensions] a new instance of Extensions
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/extensions.rb:13
  def initialize; end

  # Adds a new extension with the given name
  #
  # @param name [String, Symbol] the name of the extension
  # @raise [SnakyHash::Error] if an extension with the given name already exists
  # @return [Proc] the added extension block
  # @yield [value] block that will be called with a value to transform
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/extensions.rb:30
  def add(name, &block); end

  # Checks if an extension with the given name exists
  #
  # @param name [String, Symbol] the name of the extension to check
  # @return [Boolean] true if the extension exists, false otherwise
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/extensions.rb:42
  def has?(name); end

  # Reset the registry of extensions to an empty state
  #
  # @return [Hash] an empty hash of extensions
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/extensions.rb:20
  def reset; end

  # Runs all registered extensions in sequence on the given value
  #
  # @param value [Object] the value to transform through all extensions
  # @return [Object] the final transformed value after running all extensions
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/extensions.rb:50
  def run(value); end
end

# Provides JSON serialization and deserialization capabilities with extensible value transformation
#
# @example Basic usage
#   class MyHash < Hashie::Mash
#   extend SnakyHash::Serializer
#   end
#   hash = MyHash.load('{"key": "value"}')
#   hash.dump #=> '{"key":"value"}'
#
# source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:15
module SnakyHash::Serializer
  # Serializes a hash object to JSON
  #
  # @param obj [Hash] the hash to serialize
  # @return [String] JSON string representation of the hash
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:38
  def dump(obj); end

  # Deserializes a JSON string into a hash object
  #
  # @param raw_hash [String, nil] JSON string to deserialize
  # @return [Hash] deserialized hash object
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:47
  def load(raw_hash); end

  private

  # Checks if a value is blank (nil or empty string)
  #
  # @param value [Object] value to check
  # @return [Boolean] true if value is blank
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:131
  def blank?(value); end

  # Processes a hash for dumping, transforming its keys and/or values
  #
  # @param hash [Hash] hash to process
  # @return [Hash] processed hash with transformed values
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:150
  def dump_hash(hash); end

  # Processes a single value for dumping
  #
  # @param value [Object] value to process
  # @return [Object, nil] processed value
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:160
  def dump_value(value); end

  # Processes a hash for loading, transforming its keys and/or values
  #
  # @param hash [Hash] hash to process
  # @return [Hash] processed hash with transformed values
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:180
  def load_hash(hash); end

  # Processes a single value for loading
  #
  # @param value [Object] value to process
  # @return [Object, nil] processed value
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:204
  def load_value(value); end

  # Returns nil if value is blank, otherwise returns the value
  #
  # @param value [Object] value to check
  # @return [Object, nil] the value or nil if blank
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:142
  def presence(value); end

  class << self
    # Extends the base class with serialization capabilities
    #
    # @param base [Class] the class being extended
    # @return [void]
    #
    # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:21
    def extended(base); end
  end
end

# Provides backported methods for older Ruby versions
#
# source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:89
module SnakyHash::Serializer::BackportedInstanceMethods
  # simplecov:disable
  # Transforms values of a hash using the given block
  #
  # @note This will be run in CI on Ruby 2.3, but we only collect coverage from current Ruby
  #   Rails <= 5.2 had a transform_values method, which was added to Ruby in version 2.4.
  #   This method is a backport of that original Rails method for Ruby 2.2 and 2.3.
  # @return [Hash] new hash with transformed values
  # @return [Enumerator] if no block given
  # @yield [Object] block to transform each value
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:99
  def transform_values(&block); end
end

# Provides convenient instance methods for serialization
#
# @example Using convenience methods
#   hash = MyHash.new(key: 'value')
#   json = hash.dump #=> '{"key":"value"}'
#
# source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:116
module SnakyHash::Serializer::ConvenienceInstanceMethods
  # Serializes the current hash instance to JSON
  #
  # @return [String] JSON string representation of the hash
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:120
  def dump; end
end

# Internal module for generating extension methods
#
# source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:53
module SnakyHash::Serializer::Modulizer
  class << self
    # Creates a new module with extension management methods
    #
    # @return [Module] a module containing extension management methods
    #
    # source://snaky_hash-2.0.7/lib/snaky_hash/serializer.rb:58
    def to_extended_mod; end
  end
end

# Creates a module that provides key conversion functionality when included
#
# @note Unlike Hashie::Mash, this implementation allows for both String and Symbol key types
#
# source://snaky_hash-2.0.7/lib/snaky_hash/snake.rb:29
class SnakyHash::Snake < ::Module
  # Initialize a new Snake module
  #
  # @param key_type [Symbol] the type to convert keys to (:string or :symbol)
  # @param serializer [Boolean] whether to include serialization capabilities
  # @raise [ArgumentError] if key_type is not :string or :symbol
  # @return [Snake] a new instance of Snake
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/snake.rb:30
  def initialize(key_type: T.unsafe(nil), serializer: T.unsafe(nil)); end

  # Includes appropriate conversion methods into the base class
  #
  # @param base [Class] the class including this module
  # @return [void]
  #
  # source://snaky_hash-2.0.7/lib/snaky_hash/snake.rb:40
  def included(base); end
end

# Internal module factory for creating key conversion functionality
#
# source://snaky_hash-2.0.7/lib/snaky_hash/snake.rb:49
module SnakyHash::Snake::SnakyModulizer
  class << self
    # Creates a new module with key conversion methods based on the specified key type
    #
    # @param key_type [Symbol] the type to convert keys to (:string or :symbol)
    # @raise [ArgumentError] if key_type is not supported
    # @return [Module] a new module with conversion methods
    #
    # source://snaky_hash-2.0.7/lib/snaky_hash/snake.rb:56
    def to_mod(key_type); end
  end
end

# serializer is being introduced as an always disabled option for backwards compatibility.
# In snaky_hash v3 it will default to true.
# If you want to start using it immediately, reopen this class and add the Serializer module:
#
#   SnakyHash::StringKeyed.class_eval do
#     extend SnakyHash::Serializer
#   end
#
# source://snaky_hash-2.0.7/lib/snaky_hash/string_keyed.rb:10
class SnakyHash::StringKeyed < ::Hashie::Mash; end

# serializer is being introduced as an always disabled option for backwards compatibility.
# In snaky_hash v3 it will default to true.
# If you want to start using it immediately, reopen this class and add the Serializer module:
#
#   SnakyHash::SymbolKeyed.class_eval do
#     extend SnakyHash::Serializer
#   end
#
# source://snaky_hash-2.0.7/lib/snaky_hash/symbol_keyed.rb:10
class SnakyHash::SymbolKeyed < ::Hashie::Mash; end

# Traditional Constant Location
#
# source://snaky_hash-2.0.7/lib/snaky_hash/version.rb:7
SnakyHash::VERSION = T.let(T.unsafe(nil), String)

# source://snaky_hash-2.0.7/lib/snaky_hash/version.rb:4
module SnakyHash::Version
  extend ::VersionGem::Basic
  extend ::VersionGem::Api
end

# source://snaky_hash-2.0.7/lib/snaky_hash/version.rb:5
SnakyHash::Version::VERSION = T.let(T.unsafe(nil), String)
