# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `spring-commands-rspec` gem.
# Please instead update this file by running `bin/tapioca gem spring-commands-rspec`.

# source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:1
module Spring
  class << self
    # source://spring-4.0.0/lib/spring/configuration.rb:30
    def after_fork(&block); end

    # source://spring-4.0.0/lib/spring/configuration.rb:26
    def after_fork_callbacks; end

    # source://spring-4.0.0/lib/spring/configuration.rb:5
    def application_root; end

    # source://spring-4.0.0/lib/spring/configuration.rb:5
    def application_root=(_arg0); end

    # source://spring-4.0.0/lib/spring/configuration.rb:38
    def application_root_path; end

    # source://spring-4.0.0/lib/spring/commands.rb:19
    def command(name); end

    # source://spring-4.0.0/lib/spring/commands.rb:15
    def command?(name); end

    # source://spring-4.0.0/lib/spring/commands.rb:8
    def commands; end

    # source://spring-4.0.0/lib/spring/configuration.rb:7
    def gemfile; end

    # source://spring-4.0.0/lib/spring/configuration.rb:17
    def gemfile_lock; end

    # source://spring-4.0.0/lib/spring/configuration.rb:51
    def project_root_path; end

    # source://spring-4.0.0/lib/spring/configuration.rb:5
    def quiet; end

    # source://spring-4.0.0/lib/spring/configuration.rb:5
    def quiet=(_arg0); end

    # source://spring-4.0.0/lib/spring/commands.rb:11
    def register_command(name, command = T.unsafe(nil)); end

    # source://spring-4.0.0/lib/spring/configuration.rb:34
    def verify_environment; end

    # source://spring-4.0.0/lib/spring/watcher.rb:27
    def watch(*items); end

    # source://spring-4.0.0/lib/spring/watcher.rb:6
    def watch_interval; end

    # source://spring-4.0.0/lib/spring/watcher.rb:6
    def watch_interval=(_arg0); end

    # source://spring-4.0.0/lib/spring/watcher.rb:8
    def watch_method; end

    # source://spring-4.0.0/lib/spring/watcher.rb:11
    def watch_method=(method); end

    # source://spring-4.0.0/lib/spring/watcher.rb:23
    def watcher; end

    # source://spring-4.0.0/lib/spring/watcher.rb:7
    def watcher=(_arg0); end

    private

    # source://spring-4.0.0/lib/spring/configuration.rb:57
    def find_project_root(current_dir); end
  end
end

# source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:2
module Spring::Commands; end

# source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:3
class Spring::Commands::RSpec
  # source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:16
  def call; end

  # source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:4
  def env(*_arg0); end

  # source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:8
  def exec_name; end

  # source://spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:12
  def gem_name; end
end
