inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

require:
  - rubocop-sorbet

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    # Exclude vendor to make this work on travis
    - vendor/**/*
    - 'db/migrate/*'
    - 'db/schema.rb'
    - config/*
    - config/initializers/*
    - config/environments/*
    - config/deploy/*
    - config.ru
    - bin/*
    - db/scrapers/repos/**/*
    - default_files/*/*/*
    - spec/lib/morph/test_scrapers/*/*/*
    - lib/morph/limit_output.rb
    - app/helpers/bootstrap_flash_helper.rb

Sorbet/FalseSigil:
  Exclude:
    # Views are picked up in rubocop by haml-lint
    - app/views/**/*

Sorbet/TrueSigil:
  Enabled: true
  Exclude:
    - app/admin/*
    - spec/**/*
    - sync.ru
    - app/views/**/*

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - app/admin/*
    - spec/**/*
    - sync.ru
    - app/views/**/*
    - sorbet/tapioca/require.rb

# This conflicts with the type checking that sorbet does
Lint/SafeNavigationConsistency:
  Enabled: false

# Disabling warnings about line length because it's so common through
# the codebase currently. It would be good to fix as it would make things
# easier to read but it would take a bit of time to do.
# TODO: Enable this again
Layout/LineLength:
  Enabled: false

# We prefer double quotes here, and we're making liberal use of multi-line
# strings so it makes sense to enforce those to be consistent too
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

# Putting separators in large numbers makes sense in some circumstances but
# in others (e.g. a database id) it's just nonsensical.
Style/NumericLiterals:
  Enabled: false

# For Rails it feels a little overkill to require a description for
# each class, since so much is naming conventions.
Style/Documentation:
  Enabled: false

# TODO: Disabling temporarily
Style/StderrPuts:
  Enabled: false

# We need to turn this off so that we can put sorbet sigs on accessors
Style/AccessorGrouping:
  Enabled: false

# Disable a bunch of metrics to do with code complexity. These are all
# a bit hard-nosed. Maybe after a pass with Code Climate we can revisit.
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# In our case we seem to not be using arrays much, so there's too many
# false positives — easier to disable
Style/SlicingWithRange:
  Enabled: false
