# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StaticHelper`.
# Please instead update this file by running `bin/tapioca dsl StaticHelper`.

module StaticHelper
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
