#!/bin/bash

# Wrapper script that runs limit_output in ruby or python3
# depending on what's available in the container

if command -v ruby >/dev/null 2>&1; then
    exec ruby "$0.rb" "$@"
elif command -v python3 >/dev/null 2>&1; then
    exec python3 "$0.py" "$@"
else
    echo "ERROR: Neither ruby nor python3 is available!" >&2
    exit 1
fi
