#!/bin/sh
# Add rules for redirecting web traffic from the docker containers to the
# mitmproxy running in transparent mode

# Use iptables-mitmproxy-remote to remove rules

# Need to run this as root

# Allow established sessions
iptables -A INPUT -i eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow incoming connections on ssh, http, https
iptables -A INPUT -i eth0 -p tcp --dport ssh -j ACCEPT
iptables -A INPUT -i eth0 -p tcp --dport http -j ACCEPT
iptables -A INPUT -i eth0 -p tcp --dport https -j ACCEPT

# Block all other traffic on eth0
iptables -A INPUT -i eth0 -j DROP

# Redirect HTTP and HTTPS to mitmproxy (for new morph network)
# Note that this will still work even if the morph interface doesn't yet exist
iptables -t nat -A PREROUTING -i morph -p tcp --dport 80 -j REDIRECT --to-ports 8080
iptables -t nat -A PREROUTING -i morph -p tcp --dport 443 -j REDIRECT --to-ports 8080

# Allow DNS, HTTP and HTTPS
#iptables -A DOCKER -p tcp --sport domain -j ACCEPT
#iptables -A DOCKER -p udp --sport domain -j ACCEPT
#iptables -A DOCKER -p tcp --sport http -j ACCEPT
#iptables -A DOCKER -p tcp --sport https -j ACCEPT
# Block all other traffic
#iptables -A DOCKER -j DROP
