#!/bin/sh
# Add rules for redirecting web traffic from the docker containers to the
# mitmproxy running in transparent mode

# Use iptables-mitmproxy-remote to remove rules

# Need to run this as root

# Redirect HTTP and HTTPS to mitmproxy
iptables -t nat -A PREROUTING -i docker0 -p tcp --dport 80 -j REDIRECT --to-ports 8080
iptables -t nat -A PREROUTING -i docker0 -p tcp --dport 443 -j REDIRECT --to-ports 8080

# Allow DNS, HTTP and HTTPS
iptables -A DOCKER -p tcp --sport domain -j ACCEPT
iptables -A DOCKER -p udp --sport domain -j ACCEPT
iptables -A DOCKER -p tcp --sport http -j ACCEPT
iptables -A DOCKER -p tcp --sport https -j ACCEPT
# Block all other traffic
iptables -A DOCKER -j DROP
