#!/bin/sh
# Remove rules for redirecting web traffic from the docker containers to the
# mitmproxy running in transparent mode

# Use iptables-mitmproxy-add to add rules

# Need to run this as root

# Block all other traffic on eth0
iptables -D INPUT -i eth0 -j DROP

# Allow incoming connections on ssh, http, https
iptables -D INPUT -p tcp --dport ssh -j ACCEPT
iptables -D INPUT -p tcp --dport http -j ACCEPT
iptables -D INPUT -p tcp --dport https -j ACCEPT

# Allow established sessions
iptables -D INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

#iptables -t nat -D PREROUTING -i docker0 -p tcp --dport 80 -j REDIRECT --to-ports 8080
#iptables -t nat -D PREROUTING -i docker0 -p tcp --dport 443 -j REDIRECT --to-ports 8080

#iptables -D DOCKER -p tcp --sport domain -j ACCEPT
#iptables -D DOCKER -p udp --sport domain -j ACCEPT
#iptables -D DOCKER -p tcp --sport http -j ACCEPT
#iptables -D DOCKER -p tcp --sport https -j ACCEPT
#iptables -D DOCKER -j DROP
